### ISSUE TITLE
Release 6.0.0 to allow users to update to Python 3.12?

### ISSUE THREAD

**Issue by hartwork** [kevin1024/vcrpy#793] opened 2023-12-11 00:01 UTC
Hi! :wave:

(This is similar to issue #749 for the release of VCR.py 5.1.0.)

Since release 5.1.0 I believe we have merged the following pull requests to `master` (in order of pull request ID):

- #731
- #752
- #754
- #757
- #765
- #766
- #771
- #775
- #784
- #787
- #788
- #789
- #790
- #791
- #794
- #795
- #797
- #799
- #800
- #801

I believe it would be important to do a soon new release 6.0.0 to allow users to upgrade to Python 3.12 which VCR.py has been de-facto blocking (including one of my own projects, case https://github.com/hartwork/wnpp.debian.net/pull/806).

For anyone wondering why 6.0.0 rather than 5.2.0, we agreed at https://github.com/kevin1024/vcrpy/pull/731#issuecomment-1644430966 that merge of now-merged #731 should go along with a bump in major version.

@kevin1024 would you be up for cutting a release 6.0.0 from latest `master` shortly?
(Latest commit is 6a319043339adc3cb368eaf70bda2df3a3479af1 as of the moment.)

Thanks and best, Sebastian

CC @jairhenrique

**Comment by jairhenrique** [comment] 2023-12-11 00:05
This pr needs to be merged before this version https://github.com/kevin1024/vcrpy/pull/788

**Comment by hartwork** [comment] 2023-12-11 00:08
@jairhenrique just to understand: "needs" as in "would be beneficial" or as in "hard blocker"? Could you elaborate?

**Comment by jairhenrique** [comment] 2023-12-11 00:13
@hartwork I think it's a hard blocker because of this comment https://github.com/kevin1024/vcrpy/pull/784#issuecomment-1848976424. More people may need to recreate the cassettes if this change doesn't go through.

**Comment by hartwork** [comment] 2023-12-11 00:16
@jairhenrique thanks for elaborating, I understand! :+1: 

@parkerhancock if you could rebase your pull request #788 against latest `master` that would rock and greatly increase the chances of a soon release 6.0.0. Thanks in advance! :pray:

**Comment by hartwork** [comment] 2023-12-12 19:41
@kevin1024 I believe all release blockers are resolved now.

CC @jairhenrique

**Comment by anton-daneyko-ultramarin** [comment] 2023-12-14 19:00
What is the highest Python version that you recommend to use ATM?

**Comment by hartwork** [comment] 2023-12-14 19:14
> What is the highest Python version that you recommend to use ATM?

@anton-daneyko-ultramarin probably 3.11? Could you elaborate or give more context for the question?

**Comment by anton-daneyko-ultramarin** [comment] 2023-12-14 19:21
@hartwork 
Some context: I do not get any errors running my test suite if I use Python 3.12, however I do get some errors when I try to use PyCharm debugger with my test suite, so 3.12 is not very convenient for me for this reason (I appreciate the debugger). So I bumped it down to Python 3.11.6 and started to get some `TypeError: cannot pickle 'generator' object` errors. This prompted me to go to VCR.py issues page and read this thread from which I assume there are some problems with Python 3.12 (which I am not triggering with my test suite).

I am about to give 3.10 a try, but decided to ask you instead. I assumed it's something esasy to answer.

**Comment by hartwork** [comment] 2023-12-14 23:31
@anton-daneyko-ultramarin thanks for elaborating! Could you check if the pickle issue is the same as #737? If not, please create a _new_ issue with details. Thanks in advance!

**Comment by vEpiphyte** [comment] 2023-12-15 00:48
I'm running a big regression test with the latest vcrpy development head. I'll update this comment when it is done ( likely in the morning EST ) if i run across any issues :)

**Comment by dmelo** [comment] 2024-01-03 13:02
Any update on when we'll have the new release?

**Comment by hartwork** [comment] 2024-01-11 13:24
@kevin1024 we need you here to move forward. Do you have a minute?

**Comment by hartwork** [comment] 2024-01-18 15:24
@kevin1024 we need you here to move forward. Do you have a minute?

**Comment by graingert** [comment] 2024-01-23 12:18
I'd like to get https://github.com/kevin1024/vcrpy/pull/801 in before 6.0

**Comment by kevin1024** [comment] 2024-01-23 15:31
OK! lemme cut a release.

**Comment by graingert** [comment] 2024-01-23 15:37
Wait I broke it

**Comment by kevin1024** [comment] 2024-01-23 16:04
No worries, ping me when fixed and I'll do another release.

**Closed** 2024-01-23 16:07 UTC
Labels: releasing

**Comment by anton-daneyko-ultramarin** [comment] 2024-01-29 13:56
> @anton-daneyko-ultramarin thanks for elaborating! Could you check if the pickle issue is the same as #737? If not, please create a _new_ issue with details. Thanks in advance!

I did not have the chance to look into it back then and now I am getting bitten by this error again. I get a `TypeError: cannot pickle 'generator' object` error when using urllib3 v2.1.0 and the error goes away with urllib3 v1.26.18. The vcrpy version is 5.1.0. The stack trace leads to `before_record_request` in `vcr/config.py`. I probably won't be able to dig into it now as well, but I thought it might be helpful to leave some breadcrumbs for a future investigation or maybe @hartwork would be able to spot something fishy immediatly:
<details>
<summary>Tail of a stack trace</summary>

```
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/requests/adapters.py:486: in send
    resp = conn.urlopen(
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/urllib3/connectionpool.py:790: in urlopen
    response = self._make_request(
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/urllib3/connectionpool.py:536: in _make_request
    response = conn.getresponse()
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/vcr/stubs/__init__.py:257: in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/vcr/cassette.py:263: in can_play_response_for
    request = self._before_record_request(request)
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/site-packages/vcr/config.py:223: in before_record_request
    request = copy.deepcopy(request)
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/copy.py:172: in deepcopy
    y = _reconstruct(x, memo, *rv)
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/copy.py:271: in _reconstruct
    state = deepcopy(state, memo)
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/copy.py:146: in deepcopy
    y = copier(x, memo)
/home/acme-corp/.conda/envs/apa-proxy/lib/python3.10/copy.py:231: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
x = <generator object Client.upload_data.<locals>.json_stream at 0x7f792ac86030>
memo = {140158380145104: <[AttributeError("'Request' object has no attribute 'method'") raised in repr()] Request object at 0...', 'uri': 'http://localhost:8080/websrv/portfolios/test_cancel_task/dates?enforce-partial-import=false'}}
_nil = []
    def deepcopy(x, memo=None, _nil=[]):
        """Deep copy operation on arbitrary Python objects.
    
        See the module's __doc__ string for more info.
        """
    
        if memo is None:
            memo = {}
    
        d = id(x)
        y = memo.get(d, _nil)
        if y is not _nil:
            return y
    
        cls = type(x)
    
        copier = _deepcopy_dispatch.get(cls)
        if copier is not None:
            y = copier(x, memo)
        else:
            if issubclass(cls, type):
                y = _deepcopy_atomic(x, memo)
            else:
                copier = getattr(x, "__deepcopy__", None)
                if copier is not None:
                    y = copier(memo)
                else:
                    reductor = dispatch_table.get(cls)
                    if reductor:
                        rv = reductor(x)
                    else:
                        reductor = getattr(x, "__reduce_ex__", None)
                        if reductor is not None:
>                           rv = reductor(4)
E                           TypeError: cannot pickle 'generator' object
```
</details>

**Comment by hartwork** [comment] 2024-01-29 14:01
@anton-daneyko-ultramarin let me repeat, please create a *new* issue, your report is out of place here. Thank you!
