### ISSUE TITLE
vcrpy doesn't work under django? 

### ISSUE THREAD

**Issue by roy2006** [kevin1024/vcrpy#131] opened 2014-12-26 11:21 UTC
I'm trying to use vcrpy to accelerate the execution of my django application test suite. I'm using django 1.7 on Mac, with Python 2.7. 

I added the following couple of lines to one of my tests: 

```
     import vcr
     with vcr.use_cassette('recording.yaml'):
```

The result is an import error: 

```
    import vcr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcr/__init__.py", line 2, in <module>
    from .config import VCR
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcr/config.py", line 6, in <module>
    from .cassette import Cassette
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcr/cassette.py", line 12, in <module>
    from .patch import CassettePatcherBuilder
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcr/patch.py", line 8, in <module>
    from .stubs import VCRHTTPConnection, VCRHTTPSConnection
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcr/stubs/__init__.py", line 9, in <module>
    from six.moves.http_client import (
ImportError: No module named http_client
```

The problematic code in stubs/**init**.py is : 

```
import six
from six.moves.http_client import (
    HTTPConnection,
    HTTPSConnection,
    HTTPMessage,
    HTTPResponse,
)
```

This code seems to run fine when I'm just running it from a plain python console, but it results in the above ImportError under django.

**Comment by IvanMalison** [comment] 2015-01-03 18:04
Can you try running in a virtualenv? You can use tox to specify dependencies or just use a requirements.txt file. It seems like this might not be related to vcrpy.

**Comment by roy2006** [comment] 2015-01-04 13:18
I think you're right - it's not related to vcrpy. I played a bit with my application within a virtualenv, and outside of it, and as far as I can see there's something there that causes the issue. I wasn't able to put my finger on what it is exactly, but at some point I just gave up.

**Comment by Ram-Z** [comment] 2015-01-05 07:17
I get the same error trying to run the tests from [flexget](http://github.com/flexget/flexget) from within a virtualenv:

```
[ 7:11 ramsi@tardis <plugin-path>]% bin/paver test                                                                    ~src/flexget
---> pavement.test
Failure: ImportError (No module named http_client) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named http_client)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ramsi/src/flexget/tests/__init__.py", line 15, in <module>
    from vcr import VCR
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/vcr/__init__.py", line 2, in <module>
    from .config import VCR
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/vcr/config.py", line 6, in <module>
    from .cassette import Cassette
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/vcr/cassette.py", line 12, in <module>
    from .patch import CassettePatcherBuilder
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/vcr/patch.py", line 8, in <module>
    from .stubs import VCRHTTPConnection, VCRHTTPSConnection
  File "/home/ramsi/src/flexget/lib/python2.7/site-packages/vcr/stubs/__init__.py", line 9, in <module>
    from six.moves.http_client import (
ImportError: No module named http_client

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

My `pip freeze`:

```
APScheduler==3.0.1
BeautifulSoup==3.2.1
-e git+git@github.com:Ram-Z/Flexget.git@8c6f2569881bdb08e9b30aee19b32e06517ffdbf#egg=FlexGet-plugin-path
Jinja2==2.7.3
MarkupSafe==0.23
Paver==1.2.3
PyRSS2Gen==1.1
PyYAML==3.11
Pygments==2.0.1
SQLAlchemy==0.9.8
Sphinx==1.2.3
argparse==1.3.0
astroid==1.3.2
babelfish==0.5.3
beautifulsoup4==4.3.2
contextlib2==0.4.0
coverage==3.7.1
docutils==0.12
feedparser==5.1.3
futures==2.2.0
guessit==0.10.0
html5lib==1.0b3
http==0.02
jsonschema==2.4.0
logilab-common==0.63.2
mock==1.0.1
nose==1.3.4
nosexcover==1.0.10
path.py==7.0
pbr==0.10.7
pep8==1.5.7
plumbum==1.4.2
progressbar==2.3
pylint==1.4.0
pynzb==0.1.0
python-dateutil==2.3
python-tvrage==0.4.1
pytz==2014.10
requests==2.5.1
rpyc==3.3.0
six==1.9.0
sphinxcontrib-paverutils==1.7
stevedore==1.1.0
tmdb3==0.7.2
tzlocal==1.1.2
vcrpy==1.1.4
wrapt==1.10.2
wsgiref==0.1.2
```

**Comment by fernandogrd** [comment] 2015-01-21 23:55
Same here, using django 1.6.10 and python 2.7.9

**Comment by IvanMalison** [comment] 2015-01-30 03:07
@fernandogrd Are you running inside of a virtualenv? @roy2006 Is your application on github?

**Comment by fernandogrd** [comment] 2015-01-30 19:18
@IvanMalison Yes, under virtualenv, the project has a lot of dependencies..

**Comment by paranoidi** [comment] 2015-03-28 12:49
Seems doing this for me as well. Fresh bootstrapped flexget (so virtualenv), python 2.7.6 on Ubuntu 14.04.1 LTS (server).

**Comment by IvanMalison** [comment] 2015-04-02 00:21
@fernandogrd @paranoidi 
Are either of your projects on github/easily cloneable/runnable so that I can take a deeper look in to this?

**Comment by IvanMalison** [comment] 2015-04-02 01:21
six.py uses a custom metapath importer. I suspect that this issue has something to do with this https://bitbucket.org/gutworth/six/src/784c6a213c4527ea18f86a800f51bf16bc1df5bc/six.py?at=default#cl-164

**Comment by kevin1024** [comment] 2015-05-08 06:59
@ram-z @paranoidi @fernandogrd well I tried a fresh checkout of Flexget on a digitalocean ubuntu droplet, in a fresh virtualenv, on ubuntu 14.04 LTS and iall the tests passed for me.  Not sure what's going on here.

If you open a python shell and just do:

>>> from six.moves import http_client

what happens?  Do you get the ImportError?

**Comment by kevin1024** [comment] 2015-05-08 07:09
Here is the list of commands I ran on the digitalocean droplet:

```
apt-get update
apt-get install git python-pip python-virtualenv
git clone https://github.com/Flexget/Flexget.git
cd Flexget/
virtualenv ~/venv
pip install paver
pip install -e .
pip install nose mock vcrpy
paver test
```

It ran a bunch of tests:

```
<snip>
tests.test_validator.TestValidator.test_regexp_match ... ok
tests.test_whatcd.TestInputWhatCD.test_missing_fields ... ok
tests.test_whatcd.TestWhatCDOnline.test_invalid_login ... ok

----------------------------------------------------------------------
Ran 599 tests in 264.938s
```

¯\_(ツ)_/¯

**Comment by kevin1024** [comment] 2015-05-08 07:10
Any way this could be related to #153?

**Comment by morganwahl** [comment] 2015-05-08 15:21
I was getting a similar error message and isolated the problem like this:

```sh
morgan@morgans-desktop:~$ virtualenv six_test
morgan@morgans-desktop:~$ source six_test/bin/activate
(six_test)morgan@morgans-desktop:~$ pip freeze -l
(six_test)morgan@morgans-desktop:~$ pip install six==1.4.1
Downloading/unpacking six==1.4.1
  Downloading six-1.4.1.tar.gz
  Running setup.py (path:/home/morgan/six_test/build/six/setup.py) egg_info for package six
    
Installing collected packages: six
  Running setup.py install for six
    
Successfully installed six
Cleaning up...
(six_test)morgan@morgans-desktop:~$ pip freeze -l
six==1.4.1
(six_test)morgan@morgans-desktop:~$ python -c 'import six'
(six_test)morgan@morgans-desktop:~$ python -c 'import six.moves.http_client'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named http_client
(six_test)morgan@morgans-desktop:~$ pip install six==1.5.0
Downloading/unpacking six==1.5.0
  Downloading six-1.5.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.4.1
    Uninstalling six:
      Successfully uninstalled six
Successfully installed six
Cleaning up...
(six_test)morgan@morgans-desktop:~$ python -c 'import six.moves.http_client'
(six_test)morgan@morgans-desktop:~$ 
```

**Comment by fracmak** [comment] 2015-05-08 19:47
Forcing six==1.6.0 fixed the problem for me.

**Comment by mikelloyd** [comment] 2015-05-11 16:58
Fixed for me.

**Comment by fracmak** [comment] 2015-05-11 17:11
the problem is back for me, trying to narrow down whats causing it because it was working fine for me for a week then it broke

**Comment by fracmak** [comment] 2015-05-11 18:24
So I came up with a better solution than downgrading six. I was loading VCR in a django middleware. It appears django's version of six wins out in the sys.meta_path loader list, but for some reason it doesn't have the http_client in it's moved list. By importing vcr directly in the settings (and essentually doing nothing with it), it gets the right reference to http_client and everything is happy.

**Comment by IvanMalison** [comment] 2015-05-12 08:27
@fracmak I thought it had something to do with the meta path importer that is used.

Glad to hear you found a solution. Perhaps we should add something to the README about this?

**Comment by joseluisrt** [comment] 2015-05-22 20:15
I have exactly the same problem. Tried to downgrade to 1.6 but that did not solved the problem. In my case, the error is in rest_framework when it tries to import "from django.utils.six.moves.http_client import responses". Also tried to import rest_framework from settings.py but it did not solved the problem.

**Comment by IvanMalison** [comment] 2015-05-22 20:23
@joseluisrt Did you read/understand @fracmak's response?

**Comment by joseluisrt** [comment] 2015-05-22 22:42
I read @fracmak response, but maybe did not understand. I understood the solution was to import the library in settings. After reading again, I don't understand very well this part "It appears django's version of six wins out in the sys.meta_path loader list, but for some reason it doesn't have the http_client in it's moved list.". So I suppose that for me importing rest_framework in settings is not taking that effect. Can you help me to understand this better?

**Comment by IvanMalison** [comment] 2015-05-23 00:06
Well its complicated because importing it there doesn't necessarily guarantee that the right meta path importer will win out. Have you taken a look at the meta path loader list at that point. If you edit it manually you can probably solve the problem

**Comment by kevin1024** [comment] 2015-05-23 03:10
I think the best solution might be for VCR to stop using six.httpclient and just do our own fallback instead.  I don't think the implementation is very difficult.  Something like:

```python
# vcr/compat.py
try:
    from six.moves import  http_client as http_client
except ImportError:
    try:
        import http.client as http_client
    except ImportError:
        import httplib as http_client
```

then just update our references from `six.moves.http_client` to `vcr.compat.http_client`.

Then we don't need to worry about the version of six or this metapath business.

**Comment by IvanMalison** [comment] 2015-05-23 18:05
@joseluisrt can you print out the value of sys.meta_path when you get this error?

**Comment by joseluisrt** [comment] 2015-05-24 23:16
@IvanMalison the value of sys.meta_path just before the error is:

[<eventlet.support.six._SixMetaPathImporter object at 0xb5ff2d6c>, <six._SixMetaPathImporter object at 0xb5ee972c>]

After seeing this, I thought the problem could be the library eventlet, so I uninstalled it, but the problem was still there. May this problem exist because I forgot some other dependency to install?

**Comment by joseluisrt** [comment] 2015-06-04 20:13
The problem I had was due to rest_framework, and the solution was to downgrade to the version 3.1.1.

Sorry for this "off-topic" issue, just in case somebody finds it useful https://github.com/tomchristie/django-rest-framework/issues/2969

Thanks for your help

**Comment by brechin** [comment] 2016-10-19 22:24
FWIW, I'm using vcrpy 1.10.2 to help in testing an application built with Django 1.9.6 and Django Rest Framework 3.3.3 with no issues.

**Comment by IvanMalison** [comment] 2019-07-02 06:52
Closing bc no one seems to have this issue anymore.

**Closed by IvanMalison** 2019-07-02 06:52 UTC
Labels: ready
