### ISSUE TITLE
aiohttp: replaying doesn't work with two exact requests in replay mode "once"

### ISSUE THREAD

**Issue by nickdirienzo** [kevin1024/vcrpy#481] opened 2019-08-29 00:14 UTC
Hi again maintainers of vcrpy :)

I found this interesting problem today where in my test, I make 2 HTTP identical requests (one in the test and one in app code — perhaps this is a terrible idea and let me know if it is) and both are recorded, but when trying to replay the test it fails on the second request being made.

After debugging this for a while, it looks like what happens is we update `play_counts` for both instances of the responses being played for the first request, even though we should only track one being sent back. The code in question is here:

https://github.com/kevin1024/vcrpy/blob/baadf913ef3ed67fa599c3af18d5f9fcb005cf41/vcr/cassette.py#L267-L270

So `play_states` will be `Counter({0: 1, 1: 1})`, which feels incorrect to me since requests and responses should be one-to-one. Does that sound reasonable?

When looking up `request in self`:
 https://github.com/kevin1024/vcrpy/blob/baadf913ef3ed67fa599c3af18d5f9fcb005cf41/vcr/cassette.py#L260

It fails because of

https://github.com/kevin1024/vcrpy/blob/baadf913ef3ed67fa599c3af18d5f9fcb005cf41/vcr/cassette.py#L355-L360

I think what's happening is something specific to `aiohttp` specifically around these lines:

https://github.com/kevin1024/vcrpy/blob/baadf913ef3ed67fa599c3af18d5f9fcb005cf41/vcr/stubs/aiohttp_stubs/__init__.py#L77-L80

Perhaps it shouldn't be a `while`? It seems that it's necessary for this bug that was recently resolved: https://github.com/kevin1024/vcrpy/pull/456. 

It's been a while since I've looked at this codebase, so I'm not sure what would be best to remedy this and I haven't spent time thinking about a solution since I only just now figured out the problem. @lamenezes @arthurHamon2 it seems like y'all are familiar with this — what do you think we should do here? Or am I doing something completely wrong here and this is working as intended? How can I help, if this is a legitimate bug?

Here's my cassette data:
```yaml
interactions:
- request:
    body: '{"query": "\n    query {\n        coachAssignments {\n            uuid\n        }\n    }\n    "}'
    headers:
      Content-Type:
      - application/json
      authorization:
      - DUMMY
      x-datadog-parent-id:
      - DUMMY
      x-datadog-trace-id:
      - DUMMY
    method: POST
    uri: http://localhost:8000/graphql
  response:
    body:
      string: '{"data":{"coachAssignments":[{"uuid":"59829c6c-c904-49ea-8157-1d1ac6a2412a"}]}}'
    headers:
      Connection: keep-alive
      Content-Length: '79'
      Content-Type: application/json
      Date: Wed, 28 Aug 2019 23:00:18 GMT
      Server: nginx
      Set-Cookie: csrftoken=redacted;
        expires=Wed, 26 Aug 2020 23:00:18 GMT; Max-Age=31449600; Path=/; SameSite=Lax
      Vary: Cookie, Origin
      X-Frame-Options: SAMEORIGIN
    status:
      code: 200
      message: OK
    url: http://localhost:8000/graphql
- request:
    body: '{"query": "\n    query {\n        coachAssignments {\n            uuid\n        }\n    }\n    "}'
    headers:
      Content-Type:
      - application/json
      authorization:
      - DUMMY
      x-datadog-parent-id:
      - DUMMY
      x-datadog-trace-id:
      - DUMMY
    method: POST
    uri: http://localhost:8000/graphql
  response:
    body:
      string: '{"data":{"coachAssignments":[{"uuid":"59829c6c-c904-49ea-8157-1d1ac6a2412a"}]}}'
    headers:
      Connection: keep-alive
      Content-Length: '79'
      Content-Type: application/json
      Date: Wed, 28 Aug 2019 23:00:18 GMT
      Server: nginx
      Set-Cookie: csrftoken=redacted;
        expires=Wed, 26 Aug 2020 23:00:18 GMT; Max-Age=31449600; Path=/; SameSite=Lax
      Vary: Cookie, Origin
      X-Frame-Options: SAMEORIGIN
    status:
      code: 200
      message: OK
    url: http://localhost:8000/graphql
version: 1
```

**Comment by neozenith** [comment] 2019-08-29 01:28
Hi @nickdirienzo, thanks for the detailed issue.

It sounds like that might be the root cause behind this issue:
https://github.com/kevin1024/vcrpy/issues/475

I haven't had time to dive into figuring out a fix for it. At work we stick with just `requests` so I'm not familiar with `aiohttp`. 

I wonder if it is something to do with an async request firing off and not being handled correctly that we get a race condition that both get marked off before actually replaying and then only one returns?

**Comment by nickdirienzo** [comment] 2019-08-29 18:44
Hey @neozenith thanks for replying so quickly!

Oh interesting. I didn't realize the two were linked.

I don't think that's the case, but I may be wrong. Here's what's happening code wise (I'm sorry I didn't include this originally). It's fairly redacted, but I hope it helps?

```py
@pytest.mark.vcr()
async def test_thing(access_token):
    # Get the assigned providers for the member.
    uuids = await service.get_uuids(access_token)

    # do stuff with the above UUIDs

    # call another function that calls the same function above in its impl with its own `await`

    # assert 
    
```

Where `get_assigned_coaches_uuids` is effectively doing:
```python
        payload = json.dumps(payload)
        async with aiohttp.ClientSession(raise_for_status=True) as session:
            url = parse.urljoin(Config.get_service_host(service_name), path)
            async with session.post(url, data=payload, headers=headers) as response:
                return await response.json()
```

Putting in breakpoints in the `aiohttp` implementation we ended up calling the following function once per matching request (so in this case twice), for the first `await`: https://github.com/kevin1024/vcrpy/blob/baadf913ef3ed67fa599c3af18d5f9fcb005cf41/vcr/cassette.py#L262-L274 

If I'm understanding `asyncio`, the event loop should poll on that first await before evaluating the second request we're making, so I think it may have to do with how we're processing the file. It's entirely possible that I may be misunderstanding what's happening and your hypothesis is right. What do you think?

**Comment by nickdirienzo** [comment] 2019-08-29 18:46
FWIW, I have a workaround in how I can test things so this isn't terribly urgent. I'm happy to help with implementation and brainstorming though, if needed. I don't think I'll be able to continue debugging this actively though. There are some other things to attend to since getting around this. However, this is a good library and I'm happy to help make it better if we think this is something to fix.

**Comment by cjh79** [comment] 2019-09-03 17:24
I just ran into this as well when a bunch of my tests started failing after upgrading to 2.1.0, and came to the same conclusions as @nickdirienzo after debugging it. The fix for https://github.com/kevin1024/vcrpy/pull/456 causes this problem.

In my case this is happening because I am testing against an API that takes parameters in the request body, which vcrpy doesn't seem to use to distinguish between requests. So, multiple requests in a test, each with a different body, will be considered by vcrpy to be the same request, and trigger this bug.

**Comment by cjh79** [comment] 2019-09-03 17:33
Just found the `match_on` parameter, so I guess I can add `body` to that to get me past this.

**Comment by nickdirienzo** [comment] 2019-09-03 20:50
Hey @cjh79! I'm curious if including "body" or "raw_body" in the match list helps you get passed this! It sounds like it might if you have multiple requests to different paths. If you have a similar scenario to me (GraphQL), I wonder if it helps you get passed this or if you end up in the same boat.

**Comment by cjh79** [comment] 2019-09-03 21:17
@nickdirienzo Yes, including "body" in the match list fixed it for me. I discovered that right after my first append here.

I don't have any cases where I'm making the exact same requests more than once within a test so I am ok here now, but I suppose if someone does, using `record_mode="all"` would probably get around this bug.

**Comment by vEpiphyte** [comment] 2019-09-09 18:27
Hi! I ran across this issue today when writing a test which hit the same endpoint twice in a row.  The test worked fine when capturing data; but failed upon replay.  I've got a minimal test for vcr's aiohttp integration tests that could be used to assist with debugging this behavior.

The test itself *runs* but the happy-path cases are currently commented out.

```
def test_double_requests(tmpdir):
    url = "https://httpbin.org/get"

    with vcr.use_cassette(str(tmpdir.join("text.yaml"))):
        _, response_text1 = get(url, output="text")
        _, response_text2 = get(url, output="text")

    with vcr.use_cassette(str(tmpdir.join("text.yaml"))) as cassette:
        resp, cassette_response_text = get(url, output="text")
        assert resp.status == 200
        assert cassette_response_text == response_text1
        # This check fails because we increment the play_count
        # to 2 in the while loop!
        # assert cassette.play_count == 1

        # Now make the second test to url
        resp, cassette_response_text = get(url, output="text")

        # This check fails because we have a 599, not a 200 returned.
        # asset resp.status == 200
        assert resp.status == 599  # <----- sad path check :(

        # This check fails because we get a error message back, not the
        # actual response text
        # assert cassette_response_text == response_text2

        sad_path_message = 'No match for the request <Request (GET) https://httpbin.org/get> was found'
        assert cassette_response_text.startswith(sad_path_message)  # <--- Sad path check :(

        # The final play_count is correct
        assert cassette.play_count == 2
```

**Comment by neozenith** [comment] 2019-09-10 00:32
Hi,
I have zero exposure to aiohttp sorry and don't have the bandwidth to chase this down. 

More than happy to nurture anyone willing to open a PR though through to resolution.

My intern suggested I mark this issue as `hacktoberfest` to attract interest in resolving it next month.

We have had enough reports to warrant it being a problem which I imagine is a fraction of the people that are experiencing the same problem.

@vEpiphyte if you'd like to open up a PR with that test (even in a failing state) then we are closer to someone contributing a fix since it has a clear red/green scenario to let them know it is working once fixed.

**Comment by nickdirienzo** [comment] 2019-09-11 14:51
Oh awesome. Thanks for building a test case for this @vEpiphyte
<https://github.com/vEpiphyte>!

I agree with your intern, Josh! I won't be able to take a look at this
until next month (I think), but I'd be happy to be a sounding board in the
meantime for any contributions. :)

**Comment by vEpiphyte** [comment] 2019-09-11 15:01
This is something I can probably throw up a PR for; but I can't guarantee it would be a quick turnaround.

**Comment by neozenith** [comment] 2019-09-29 07:14
I've exhausted all the bandwidth my employer had allocated me to get VCRpy updated. Unless it is approving PRs I have no bandwidth on issues anymore sorry.

Just leaving a comment here so others are aware and I'm not ghosting the project but setting expectations.

**Comment by nickdirienzo** [comment] 2019-12-01 07:59
Hey y'all, I found some energy and time to work on this over the weekend! I will put up a PR on Dec 1; I'll include my findings, what I learned, and risks in the PR description.

Thanks @vEpiphyte for the test case. This made it easier to ensure I was on the right track. :) 

I'll assign myself so folks know this is being worked on.

**Comment by nickdirienzo** [comment] 2019-12-01 22:49
Hey y'all. I finally found time and energy to resolving this issue via #495. 

@cjh79, @vEpiphyte: if you have time and are interested in seeing if my fork resolves your issue that would be awesome. No worries if not! There are test cases that should resemble the behavior we both identified.

**Closed** 2019-12-13 04:01 UTC
Labels: aiohttp, hacktoberfest, ready
