### ISSUE TITLE
Fix compatibility with setuptools 72

### ISSUE THREAD

**Issue by strujilloc** [kevin1024/vcrpy#855] opened 2024-07-29 07:22 UTC
Due to [Test command removal](https://github.com/pypa/setuptools/issues/4519) in setuptools, installation fails with version 72:
```
Collecting vcrpy
  Using cached vcrpy-6.0.1.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/pb/0cllx_zx6vb88jht981qy96c0000gn/T/pip-build-env-c0ajc0p7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/pb/0cllx_zx6vb88jht981qy96c0000gn/T/pip-build-env-c0ajc0p7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/pb/0cllx_zx6vb88jht981qy96c0000gn/T/pip-build-env-c0ajc0p7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/pb/0cllx_zx6vb88jht981qy96c0000gn/T/pip-build-env-c0ajc0p7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by Toeplitz** [comment] 2024-07-29 08:51
what's the most correct fix for this currently?

**Comment by agroszer** [comment] 2024-07-29 09:20
Looks like GH actions just use `exec pytest` so is that piece of code still in use?

**Comment by DanieleIsoni** [comment] 2024-07-29 09:47
I think this is a duplicate of #854

**Comment by agroszer** [comment] 2024-07-29 09:49
> I think this is a duplicate of #854

It is, but title is misleading.

**Comment by bitphage** [comment] 2024-07-29 10:07
Fix via setting PIP_CONSTRAINTS https://github.com/pypa/setuptools/issues/4519#issuecomment-2254983472

**Comment by omidkk** [comment] 2024-07-29 10:22
@agroszer seems pre-commit and some tests failed after your PR.

**Comment by deronnax** [comment] 2024-07-29 16:07
The problematic setuptools version has been yanked.

**Closed** 2024-07-29 16:35 UTC
