### ISSUE TITLE
requests 2.7: body of response is not getting gunzipped

### ISSUE THREAD

**Issue by klvbdmh** [kevin1024/vcrpy#152] opened 2015-05-06 00:28 UTC
I made a simple function that returns a page doctype. A test for that function works fine without vcrpy. It fails with vcrpy because a different doctype is returned.

This is the function inside `amzn.py` file:

    import requests
    from lxml import etree, html

    def get_doctype():
        r = requests.get('http://www.amazon.com')
        html_element = html.fromstring(r.text)
        tree = etree.ElementTree(html_element)
        doctype = tree.docinfo.doctype
        return doctype

And this is the test for that function. It's inside `test_amzn.py` file:

    from amzn import get_doctype

    def test_amazon_doctype():
        assert get_doctype() == 'random string'

Predictably, it fails:

    ============================= test session starts ==============================
    platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0
    rootdir: /home/as/Projects/scrapping, inifile: 
    collected 1 items
    
    Projects/scrapping/test_amzn.py F

    =================================== FAILURES ===================================
    _____________________________ test_amazon_doctype ______________________________

        def test_amazon_doctype():
    >       assert get_doctype() == 'random string'
    E       assert '<!DOCTYPE html>' == 'random string'
    E         - <!DOCTYPE html>
    E         + random string

    Projects/scrapping/test_amzn.py:7: AssertionError
    =========================== 1 failed in 1.73 seconds ===========================

So let's fix it:

    def test_amazon_doctype():
        assert get_doctype() == '<!DOCTYPE html>'

Now it passes successfully. The test is written correctly:

    ============================= test session starts ==============================
    platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0
    rootdir: /home/as/Projects/scrapping, inifile: 
    collected 1 items

    Projects/scrapping/test_amzn.py .

    =========================== 1 passed in 1.60 seconds ===========================

Now let's apply vcrpy's cassette:

    from amzn import get_doctype
    import vcr

    @vcr.use_cassette('doctype.yaml')
    def test_amazon_doctype():
        assert get_doctype() == '<!DOCTYPE html>'

The test fails - a different doctype is returned:

    ============================= test session starts ==============================
    platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0
    rootdir: /home/as/Projects/scrapping, inifile: 
    collected 1 items

    Projects/scrapping/test_amzn.py F

    =================================== FAILURES ===================================
    _____________________________ test_amazon_doctype ______________________________

        @vcr.use_cassette('doctype.yaml')
        def test_amazon_doctype():
    >       assert get_doctype() == '<!DOCTYPE html>'
    E       assert '<!DOCTYPE ht...0/loose.dtd">' == '<!DOCTYPE html>'
    E         - <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
    E         + <!DOCTYPE html>

    Projects/scrapping/test_amzn.py:7: AssertionError
    =========================== 1 failed in 0.52 seconds ===========================

I've checked the body of the response inside .yaml file. Here's the beginning of the body after decoding and unpacking it:

    b'\n\n\n\n  \n  \n\n\n  \n  \n\n\n\n      <!doctype html><!--[if lt IE 7]><html class="a-no-js a-lt-ie10 a-lt-ie9 a-lt-ie8 a-lt-ie7

That's definitely a different doctype from the one returned after applying vcrpy's cassette.

Of course, if I modify the test:

    def test_amazon_doctype():
        assert get_doctype() == '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">'

and run it without vcrpy, it fails:

    ============================= test session starts ==============================
    platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0
    rootdir: /home/as/Projects/scrapping, inifile: 
    collected 1 items

    Projects/scrapping/test_amzn.py F

    =================================== FAILURES ===================================
    _____________________________ test_amazon_doctype ______________________________

        def test_amazon_doctype():
    >       assert get_doctype() == '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">'
    E       assert '<!DOCTYPE html>' == '<!DOCTYPE html PUBL...C-html40/loose.dtd">'
    E         - <!DOCTYPE html>
    E         + <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">

    Projects/scrapping/test_amzn.py:7: AssertionError
    =========================== 1 failed in 1.98 seconds ===========================

**Comment by kevin1024** [comment] 2015-05-06 05:21
well that's pretty weird.

**Comment by kevin1024** [comment] 2015-05-06 05:25
Yup, I can reproduce.

**Comment by kevin1024** [comment] 2015-05-06 05:42
Appears to be an incompatibility with the latest version of requests.  Downgrading to 2.2.1 works.

**Comment by kevin1024** [comment] 2015-05-06 06:46
Yeah, the problem is that the body is not getting unzipped, so lxml goes all weird trying to parse it and sticks a weird doctype on there.

**Comment by kevin1024** [comment] 2015-05-06 07:18
I think this only happens on servers that send `transfer-encoding: chunked`.

**Comment by kevin1024** [comment] 2015-05-06 07:34
I think this is fixed in 5b9b6cd8b5d70262a82f4f6c600a7bb677c71f74

**Comment by kevin1024** [comment] 2015-05-06 07:34
If Travis agrees I'll do a release.

**Closed by kevin1024** 2015-05-06 07:34 UTC
Labels: bug

**Comment by klvbdmh** [comment] 2015-05-06 10:51
Yep, that fixes it.
