### ISSUE TITLE
Automatic Naming (with parametrized ?) breaks cloning in windows

### ISSUE THREAD

**Issue by slamer59** [kevin1024/vcrpy#630] opened 2022-02-07 13:55 UTC
In saleor, vcr is used and produced names breaks because windows doesnot accept some characters [, ] :, etc... 

https://github.com/saleor/saleor/pull/9086

Do you have a workaround ? Or an idea to improve automatic name generation ? 

You can see the results here:
https://github.com/saleor/saleor/tree/main/saleor/graphql/core/tests/cassettes

The test : 
https://github.com/saleor/saleor/blob/237a8cce5fdc88d2995903c4c872344669f6fd08/saleor/graphql/core/tests/test_core.py#L388

**Comment by hartwork** [comment] 2023-12-09 15:09
Hi @slamer59,

from that description it is not clear to me what the problem *in VCR* would be and commit https://github.com/saleor/saleor/commit/f6c268d2ea08f3417dee1a761617e98a6b78b2c7 seems to indicate that it's *outside of VCR*. If this needs fixing, it will need a [minimal_reproducible_example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). I'm adding label "need info" for now since this is blocking to go further.

**Comment by slamer59** [comment] 2023-12-09 17:18
Hello, I understand. 

It was 2 years ago now so hard for me to come back on this.

Thanks anyway

**Comment by hartwork** [comment] 2023-12-09 17:41
@slamer59 thanks for your reply, I'll close this as obsolete then.

**Closed by hartwork** 2023-12-09 17:41 UTC
Labels: need info
