### ISSUE TITLE
How to disable usage of vcr/cassetes

### ISSUE THREAD

**Issue by humbienri** [kevin1024/vcrpy#462] opened 2019-07-31 17:56 UTC
Hello!

This question seems silly I think but I can't find any documentation on the matter.  How does one then disable or turn off usage of vcr/cassettes without modifying the code?  I sort of get the usage and purpose of VCRpy but still wonder, "then what?".

Ultimately I want my HTTP REST API tests to test the actual REST API.  So once I've sprinkled in some decorators and sped up the running of my tests (or 1 test in my case :) ), then what?  I don't know about ya'll but I don't code that fast to worry about being throttled or blocked.  So clearly I am missing some understanding.

How do I tell VCRpy (config?), "Okay, now for real, stop using the cassettes and really hit the actual API."

I've really enjoyed learning about VCRpy so please, advise?  Thank you in advance.

**Comment by arthurHamon2** [comment] 2019-08-09 19:17
Seems that you need to set the VCR mode `all`, see the documentation here : https://vcrpy.readthedocs.io/en/latest/usage.html#record-modes
Although, the aim of this project is to build tests that interact with the network but in a reliable and deterministic way. You don't want your CI to fail because of a network failure or a unavailable service that you do not control. With vcrpy, your tests will always be deterministic after the first run and prevent regression, for instance updating a request body by mistake. Hope it answers your question ☺️

**Comment by neozenith** [comment] 2019-08-19 19:08
Hi,

Personally I use vcrpy in conjunction with a pytest plugin.

 - https://github.com/ktosiek/pytest-vcr
 - https://github.com/kiwicom/pytest-recording

In the case of the first one:

```
# Cache cassettes once
pytest --vcr-record=once

# Turn off network and use only recorded cassettes
# Add this as a default in your tox.ini, setup.cfg or pytest.ini
pytest --vcr-record=none

# Disable cassettes and use normal network 
pytest --disable-vcr
```

As Arthur mentioned, there is the benefit of faster tests, and checking for regressions in how your requests are composed. Or detecting new requests firing off that shouldn't.

I can also see the point of disabling vcrpy and to be honest I also do a full run of `pytest --disable-vcr` during my lunch break every now and then as well.

I'm going to close this issue as resolved but please feel free to comment again if there are more questions.

**Closed by neozenith** 2019-08-19 19:08 UTC

**Comment by humbienri** [comment] 2019-08-19 19:15
My apologies for not replying sooner.  Thank you both for the insights!  I guess I misunderstood the purpose of VCRpy.  It seems that VCRpy is to speed up the execution of your REST API tests, if you don't want to hit the real/actual API endpoints.  But also to buffer yourself from others' or 3rd party/external API endpoints that may not really be relevant as part of your company's API endpoints?

So create VCRpy cassettes for some API endpoints but not all if the goal is to test your own/company's endpoints?

I appreciate the comments and agree with closing this ticket.  Thank you!
-Humberto

**Comment by LewisCowlesMotive** [comment] 2023-09-07 14:15
is there a combination of `  --disable-vcr and --block-network` that can be offered? To test that the test fails when network is not available and it's not using vcr?
